import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(383, 201)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup1 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup1.setObjectName("buttonGroup1")
        self.buttonGroup1.addButton(self.radioButton)
        self.verticalLayout_5.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup1.addButton(self.radioButton_2)
        self.verticalLayout_5.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup1.addButton(self.radioButton_3)
        self.verticalLayout_5.addWidget(self.radioButton_3)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup2.setObjectName("buttonGroup2")
        self.buttonGroup2.addButton(self.radioButton_6)
        self.verticalLayout_6.addWidget(self.radioButton_6)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup2.addButton(self.radioButton_4)
        self.verticalLayout_6.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup2.addButton(self.radioButton_5)
        self.verticalLayout_6.addWidget(self.radioButton_5)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup3.setObjectName("buttonGroup3")
        self.buttonGroup3.addButton(self.radioButton_9)
        self.verticalLayout_7.addWidget(self.radioButton_9)
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup3.addButton(self.radioButton_7)
        self.verticalLayout_7.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup3.addButton(self.radioButton_8)
        self.verticalLayout_7.addWidget(self.radioButton_8)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Текстовый флаг "))
        self.label.setText(_translate("MainWindow", "Цвет № 1"))
        self.radioButton.setText(_translate("MainWindow", "Синий"))
        self.radioButton_2.setText(_translate("MainWindow", "Красный"))
        self.radioButton_3.setText(_translate("MainWindow", "Зелёный"))
        self.label_2.setText(_translate("MainWindow", "Цвет № 2"))
        self.radioButton_6.setText(_translate("MainWindow", "Синий"))
        self.radioButton_4.setText(_translate("MainWindow", "Красный"))
        self.radioButton_5.setText(_translate("MainWindow", "Зелёный"))
        self.label_3.setText(_translate("MainWindow", "Цвет № 3"))
        self.radioButton_9.setText(_translate("MainWindow", "Синий"))
        self.radioButton_7.setText(_translate("MainWindow", "Красный"))
        self.radioButton_8.setText(_translate("MainWindow", "Зелёный"))
        self.pushButton.setText(_translate("MainWindow", "Нарисовать"))


class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.pushButton.clicked.connect(self.btnclik)

    def btnclik(self):
        res = 'Цвета: '
        res += self.buttonGroup1.checkedButton().text()
        res += ', ' + self.buttonGroup2.checkedButton().text()
        res += ' и ' + self.buttonGroup3.checkedButton().text()
        self.label_4.setText(res)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.exit(app.exec_())
